version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  data: